<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('category')->insert([
            [ 'group' => 'country_code', 'key' => 'Afghanistan', 'value' => '93'],
            [ 'group' => 'country_code', 'key' => 'Albania', 'value' => '355'],
            [ 'group' => 'country_code', 'key' => 'Algeria', 'value' => '213'],
            [ 'group' => 'country_code', 'key' => 'American Samoa', 'value' => '1 684'],
            [ 'group' => 'country_code', 'key' => 'Andorra', 'value' => '376'],
            [ 'group' => 'country_code', 'key' => 'Angola', 'value' => '244'],
            [ 'group' => 'country_code', 'key' => 'Anguilla', 'value' => '1264'],
            [ 'group' => 'country_code', 'key' => 'Antarctica', 'value' => '672'],
            [ 'group' => 'country_code', 'key' => 'Antigua and Barbuda', 'value' => '1268'],
            [ 'group' => 'country_code', 'key' => 'Antilles, Netherlands', 'value' => '599'],
            [ 'group' => 'country_code', 'key' => 'Argentina', 'value' => '54'],
            [ 'group' => 'country_code', 'key' => 'Armenia', 'value' => '374'],
            [ 'group' => 'country_code', 'key' => 'Aruba', 'value' => '297'],
            [ 'group' => 'country_code', 'key' => 'Australia', 'value' => '61'],
            [ 'group' => 'country_code', 'key' => 'Austria', 'value' => '43'],
            [ 'group' => 'country_code', 'key' => 'Azerbaijan', 'value' => '994'],
            [ 'group' => 'country_code', 'key' => 'Bahamas', 'value' => '1242'],
            [ 'group' => 'country_code', 'key' => 'Bahrain', 'value' => '973'],
            [ 'group' => 'country_code', 'key' => 'Bangladesh', 'value' => '880'],
            [ 'group' => 'country_code', 'key' => 'Barbados', 'value' => '1246'],
            [ 'group' => 'country_code', 'key' => 'Belarus', 'value' => '375'],
            [ 'group' => 'country_code', 'key' => 'Belgium', 'value' => '375'],
            [ 'group' => 'country_code', 'key' => 'Belize', 'value' => '501'],
            [ 'group' => 'country_code', 'key' => 'Benin', 'value' => '229'],
            [ 'group' => 'country_code', 'key' => 'Bermuda', 'value' => '1 441'],
            [ 'group' => 'country_code', 'key' => 'Bhutan', 'value' => '975'],
            [ 'group' => 'country_code', 'key' => 'Bolivia', 'value' => '591'],
            [ 'group' => 'country_code', 'key' => 'Bosnia and Herzegovina', 'value' => '387'],
            [ 'group' => 'country_code', 'key' => 'Botswana', 'value' => '267'],
            [ 'group' => 'country_code', 'key' => 'Brazil', 'value' => '55'],
            [ 'group' => 'country_code', 'key' => 'British Indian Ocean Territory', 'value' => '246'],
            [ 'group' => 'country_code', 'key' => 'British Virgin Islands', 'value' => '1 284'],
            [ 'group' => 'country_code', 'key' => 'Brunei Darussalam', 'value' => '673'],
            [ 'group' => 'country_code', 'key' => 'Bulgaria', 'value' => '359'],
            [ 'group' => 'country_code', 'key' => 'Burkina Faso', 'value' => '226'],
            [ 'group' => 'country_code', 'key' => 'Burundi', 'value' => '257'],
            [ 'group' => 'country_code', 'key' => 'Cambodia', 'value' => '855'],
            [ 'group' => 'country_code', 'key' => 'Cameroon', 'value' => '237'],
            [ 'group' => 'country_code', 'key' => 'Canada', 'value' => '1'],
            [ 'group' => 'country_code', 'key' => 'Cape Verde', 'value' => '238'],
            [ 'group' => 'country_code', 'key' => 'Cayman Islands', 'value' => '1 345'],
            [ 'group' => 'country_code', 'key' => 'Central African Republic', 'value' => '236'],
            [ 'group' => 'country_code', 'key' => 'Chad', 'value' => '235'],
            [ 'group' => 'country_code', 'key' => 'Chile', 'value' => '56'],
            [ 'group' => 'country_code', 'key' => 'China', 'value' => '86'],
            [ 'group' => 'country_code', 'key' => 'Christmas Island', 'value' => '64'],
            [ 'group' => 'country_code', 'key' => 'Cocos (Keeling) Islands', 'value' => '61'],
            [ 'group' => 'country_code', 'key' => 'Colombia', 'value' => '57'],
            [ 'group' => 'country_code', 'key' => 'Comoros', 'value' => '269'],
            [ 'group' => 'country_code', 'key' => 'Congo', 'value' => '242'],
            [ 'group' => 'country_code', 'key' => 'Cook Islands', 'value' => '682'],
            [ 'group' => 'country_code', 'key' => 'Costa Rica', 'value' => '506'],
            [ 'group' => 'country_code', 'key' => 'Cote D\'Ivoire', 'value' => '225'],
            [ 'group' => 'country_code', 'key' => 'Croatia', 'value' => '385'],
            [ 'group' => 'country_code', 'key' => 'Cuba', 'value' => '53'],
            [ 'group' => 'country_code', 'key' => 'Cyprus', 'value' => '357'],
            [ 'group' => 'country_code', 'key' => 'Czech Republic', 'value' => '420'],
            [ 'group' => 'country_code', 'key' => 'Denmark', 'value' => '45'],
            [ 'group' => 'country_code', 'key' => 'Djibouti', 'value' => '253'],
            [ 'group' => 'country_code', 'key' => 'Dominica', 'value' => '1 767'],
            [ 'group' => 'country_code', 'key' => 'Dominican Republic', 'value' => '1 809'],
            [ 'group' => 'country_code', 'key' => 'East Timor (Timor-Leste)', 'value' => '670'],
            [ 'group' => 'country_code', 'key' => 'Ecuador', 'value' => '593'],
            [ 'group' => 'country_code', 'key' => 'Egypt', 'value' => '20'],
            [ 'group' => 'country_code', 'key' => 'El Salvador', 'value' => '503'],
            [ 'group' => 'country_code', 'key' => 'Equatorial Guinea', 'value' => '240'],
            [ 'group' => 'country_code', 'key' => 'Eritrea', 'value' => '291'],
            [ 'group' => 'country_code', 'key' => 'Estonia', 'value' => '372'],
            [ 'group' => 'country_code', 'key' => 'Ethiopia', 'value' => '251'],
            [ 'group' => 'country_code', 'key' => 'Falkland Islands (Malvinas)', 'value' => '500'],
            [ 'group' => 'country_code', 'key' => 'Faroe Islands', 'value' => '298'],
            [ 'group' => 'country_code', 'key' => 'Fiji', 'value' => '679'],
            [ 'group' => 'country_code', 'key' => 'Finland', 'value' => '358'],
            [ 'group' => 'country_code', 'key' => 'France', 'value' => '33'],
            [ 'group' => 'country_code', 'key' => 'French Guiana', 'value' => '594'],
            [ 'group' => 'country_code', 'key' => 'French Polynesia', 'value' => '689'],
            [ 'group' => 'country_code', 'key' => 'Gabon', 'value' => '241'],
            [ 'group' => 'country_code', 'key' => 'Gambia, the', 'value' => '220'],
            [ 'group' => 'country_code', 'key' => 'Georgia', 'value' => '995'],
            [ 'group' => 'country_code', 'key' => 'Germany', 'value' => '49'],
            [ 'group' => 'country_code', 'key' => 'Ghana', 'value' => '233'],
            [ 'group' => 'country_code', 'key' => 'Gibraltar', 'value' => '350'],
            [ 'group' => 'country_code', 'key' => 'Greece', 'value' => '30'],
            [ 'group' => 'country_code', 'key' => 'Greenland', 'value' => '299'],
            [ 'group' => 'country_code', 'key' => 'Grenada', 'value' => '1 473'],
            [ 'group' => 'country_code', 'key' => 'Guadeloupe', 'value' => '590'],
            [ 'group' => 'country_code', 'key' => 'Guam', 'value' => '1 671'],
            [ 'group' => 'country_code', 'key' => 'Guatemala', 'value' => '502'],
            [ 'group' => 'country_code', 'key' => 'Guernsey and Alderney', 'value' => '5399'],
            [ 'group' => 'country_code', 'key' => 'Guinea', 'value' => '224'],
            [ 'group' => 'country_code', 'key' => 'Guinea-Bissau', 'value' => '245'],
            [ 'group' => 'country_code', 'key' => 'Guinea, Equatorial', 'value' => '240'],
            [ 'group' => 'country_code', 'key' => 'Guiana, French', 'value' => '594'],
            [ 'group' => 'country_code', 'key' => 'Guyana', 'value' => '592'],
            [ 'group' => 'country_code', 'key' => 'Haiti', 'value' => '509'],
            [ 'group' => 'country_code', 'key' => 'Holy See (Vatican City State)', 'value' => '379'],
            [ 'group' => 'country_code', 'key' => 'Holland', 'value' => '31'],
            [ 'group' => 'country_code', 'key' => 'Honduras', 'value' => '504'],
            [ 'group' => 'country_code', 'key' => 'Hong Kong, (China)', 'value' => '852'],
            [ 'group' => 'country_code', 'key' => 'Hungary', 'value' => '36'],
            [ 'group' => 'country_code', 'key' => 'Iceland', 'value' => '354'],
            [ 'group' => 'country_code', 'key' => 'India', 'value' => '91'],
            [ 'group' => 'country_code', 'key' => 'Indonesia', 'value' => '62'],
            [ 'group' => 'country_code', 'key' => 'Iran', 'value' => '98'],
            [ 'group' => 'country_code', 'key' => 'Iraq', 'value' => '964'],
            [ 'group' => 'country_code', 'key' => 'Ireland', 'value' => '353'],
            [ 'group' => 'country_code', 'key' => 'Isle of Man', 'value' => '44'],
            [ 'group' => 'country_code', 'key' => 'Israel', 'value' => '972'],
            [ 'group' => 'country_code', 'key' => 'Italy', 'value' => '39'],
            [ 'group' => 'country_code', 'key' => 'Jamaica', 'value' => '1 876'],
            [ 'group' => 'country_code', 'key' => 'Japan', 'value' => '81'],
            [ 'group' => 'country_code', 'key' => 'Jersey', 'value' => '44'],
            [ 'group' => 'country_code', 'key' => 'Jordan', 'value' => '962'],
            [ 'group' => 'country_code', 'key' => 'Kazakhstan', 'value' => '7'],
            [ 'group' => 'country_code', 'key' => 'Kenya', 'value' => '254'],
            [ 'group' => 'country_code', 'key' => 'Kiribati', 'value' => '686'],
            [ 'group' => 'country_code', 'key' => 'Korea(North)', 'value' => '850'],
            [ 'group' => 'country_code', 'key' => 'Korea(South)', 'value' => '82'],
            [ 'group' => 'country_code', 'key' => 'Kosovo', 'value' => '381'],
            [ 'group' => 'country_code', 'key' => 'Kuwait', 'value' => '965'],
            [ 'group' => 'country_code', 'key' => 'Kyrgyzstan', 'value' => '996'],
            [ 'group' => 'country_code', 'key' => 'Lao People\'s Democratic Republic', 'value' => '856'],
            [ 'group' => 'country_code', 'key' => 'Latvia', 'value' => '371'],
            [ 'group' => 'country_code', 'key' => 'Lebanon', 'value' => '961'],
            [ 'group' => 'country_code', 'key' => 'Lesotho', 'value' => '266'],
            [ 'group' => 'country_code', 'key' => 'Liberia', 'value' => '231'],
            [ 'group' => 'country_code', 'key' => 'Libyan Arab Jamahiriya', 'value' => '218'],
            [ 'group' => 'country_code', 'key' => 'Liechtenstein', 'value' => '423'],
            [ 'group' => 'country_code', 'key' => 'Lithuania', 'value' => '370'],
            [ 'group' => 'country_code', 'key' => 'Luxembourg', 'value' => '352'],
            [ 'group' => 'country_code', 'key' => 'Macao, (China)', 'value' => '853'],
            [ 'group' => 'country_code', 'key' => 'Macedonia, TFYR', 'value' => '389'],
            [ 'group' => 'country_code', 'key' => 'Madagascar', 'value' => '261'],
            [ 'group' => 'country_code', 'key' => 'Malawi', 'value' => '265'],
            [ 'group' => 'country_code', 'key' => 'Malaysia', 'value' => '60'],
            [ 'group' => 'country_code', 'key' => 'Maldives', 'value' => '960'],
            [ 'group' => 'country_code', 'key' => 'Mali', 'value' => '223'],
            [ 'group' => 'country_code', 'key' => 'Malta', 'value' => '356'],
            [ 'group' => 'country_code', 'key' => 'Marshall Islands', 'value' => '692'],
            [ 'group' => 'country_code', 'key' => 'Martinique', 'value' => '596'],
            [ 'group' => 'country_code', 'key' => 'Mauritania', 'value' => '222'],
            [ 'group' => 'country_code', 'key' => 'Mauritius', 'value' => '230'],
            [ 'group' => 'country_code', 'key' => 'Mayotte', 'value' => '262'],
            [ 'group' => 'country_code', 'key' => 'Mexico', 'value' => '52'],
            [ 'group' => 'country_code', 'key' => 'Micronesia', 'value' => '691'],
            [ 'group' => 'country_code', 'key' => 'Moldova', 'value' => '373'],
            [ 'group' => 'country_code', 'key' => 'Monaco', 'value' => '377'],
            [ 'group' => 'country_code', 'key' => 'Mongolia', 'value' => '976'],
            [ 'group' => 'country_code', 'key' => 'Montenegro', 'value' => '382'],
            [ 'group' => 'country_code', 'key' => 'Montserrat', 'value' => '1 664'],
            [ 'group' => 'country_code', 'key' => 'Morocco', 'value' => '212'],
            [ 'group' => 'country_code', 'key' => 'Mozambique', 'value' => '258'],
            [ 'group' => 'country_code', 'key' => 'Myanmar', 'value' => '95'],
            [ 'group' => 'country_code', 'key' => 'Namibia', 'value' => '264'],
            [ 'group' => 'country_code', 'key' => 'Nauru', 'value' => '674'],
            [ 'group' => 'country_code', 'key' => 'Nepal', 'value' => '977'],
            [ 'group' => 'country_code', 'key' => 'Netherlands', 'value' => '31'],
            [ 'group' => 'country_code', 'key' => 'Netherlands Antilles', 'value' => '599'],
            [ 'group' => 'country_code', 'key' => 'New Caledonia', 'value' => '687'],
            [ 'group' => 'country_code', 'key' => 'New Zealand', 'value' => '64'],
            [ 'group' => 'country_code', 'key' => 'Nicaragua', 'value' => '505'],
            [ 'group' => 'country_code', 'key' => 'Niger', 'value' => '227'],
            [ 'group' => 'country_code', 'key' => 'Nigeria', 'value' => '234'],
            [ 'group' => 'country_code', 'key' => 'Niue', 'value' => '683'],
            [ 'group' => 'country_code', 'key' => 'Norfolk Island', 'value' => '672'],
            [ 'group' => 'country_code', 'key' => 'Northern Mariana Islands', 'value' => '1 670'],
            [ 'group' => 'country_code', 'key' => 'Norway', 'value' => '47'],
            [ 'group' => 'country_code', 'key' => 'Oman', 'value' => '968'],
            [ 'group' => 'country_code', 'key' => 'Pakistan', 'value' => '92'],
            [ 'group' => 'country_code', 'key' => 'Palau', 'value' => '680'],
            [ 'group' => 'country_code', 'key' => 'Palestinian Territory', 'value' => '970'],
            [ 'group' => 'country_code', 'key' => 'Panama', 'value' => '507'],
            [ 'group' => 'country_code', 'key' => 'Papua New Guinea', 'value' => '675'],
            [ 'group' => 'country_code', 'key' => 'Paraguay', 'value' => '595'],
            [ 'group' => 'country_code', 'key' => 'Peru', 'value' => '51'],
            [ 'group' => 'country_code', 'key' => 'Philippines', 'value' => '63'],
            [ 'group' => 'country_code', 'key' => 'Pitcairn Island', 'value' => '872'],
            [ 'group' => 'country_code', 'key' => 'Poland', 'value' => '48'],
            [ 'group' => 'country_code', 'key' => 'Portugal', 'value' => '351'],
            [ 'group' => 'country_code', 'key' => 'Puerto Rico', 'value' => '1787'],
            [ 'group' => 'country_code', 'key' => 'Qatar', 'value' => '974'],
            [ 'group' => 'country_code', 'key' => 'Reunion', 'value' => '262'],
            [ 'group' => 'country_code', 'key' => 'Romania', 'value' => '40'],
            [ 'group' => 'country_code', 'key' => 'Russia', 'value' => '7'],
            [ 'group' => 'country_code', 'key' => 'Rwanda', 'value' => '250'],
            [ 'group' => 'country_code', 'key' => 'Sahara', 'value' => '212'],
            [ 'group' => 'country_code', 'key' => 'Saint Helena', 'value' => '290'],
            [ 'group' => 'country_code', 'key' => 'Saint Kitts and Nevis', 'value' => '1869'],
            [ 'group' => 'country_code', 'key' => 'Saint Lucia', 'value' => '1758'],
            [ 'group' => 'country_code', 'key' => 'Saint Pierre and Miquelon', 'value' => '508'],
            [ 'group' => 'country_code', 'key' => 'Saint Vincent and the Grenadines', 'value' => '1784'],
            [ 'group' => 'country_code', 'key' => 'Samoa', 'value' => '685'],
            [ 'group' => 'country_code', 'key' => 'San Marino', 'value' => '374'],
            [ 'group' => 'country_code', 'key' => 'Sao Tome and Principe', 'value' => '239'],
            [ 'group' => 'country_code', 'key' => 'Saudi Arabia', 'value' => '966'],
            [ 'group' => 'country_code', 'key' => 'Senegal', 'value' => '221'],
            [ 'group' => 'country_code', 'key' => 'Serbia', 'value' => '381'],
            [ 'group' => 'country_code', 'key' => 'Seychelles', 'value' => '248'],
            [ 'group' => 'country_code', 'key' => 'Sierra Leone', 'value' => '232'],
            [ 'group' => 'country_code', 'key' => 'Singapore', 'value' => '65'],
            [ 'group' => 'country_code', 'key' => 'Slovakia', 'value' => '421'],
            [ 'group' => 'country_code', 'key' => 'Slovenia', 'value' => '386'],
            [ 'group' => 'country_code', 'key' => 'Solomon Islands', 'value' => '677'],
            [ 'group' => 'country_code', 'key' => 'Somalia', 'value' => '252'],
            [ 'group' => 'country_code', 'key' => 'South Africa', 'value' => '27'],
            [ 'group' => 'country_code', 'key' => 'S. Georgia and S. Sandwich Is.', 'value' => '500'],
            [ 'group' => 'country_code', 'key' => 'Spain', 'value' => '34'],
            [ 'group' => 'country_code', 'key' => 'Sri Lanka (ex-Ceilan)', 'value' => '94'],
            [ 'group' => 'country_code', 'key' => 'Sudan', 'value' => '249'],
            [ 'group' => 'country_code', 'key' => 'Suriname', 'value' => '597'],
            [ 'group' => 'country_code', 'key' => 'Svalbard and Jan Mayen Islands', 'value' => '79'],
            [ 'group' => 'country_code', 'key' => 'Swaziland', 'value' => '41'],
            [ 'group' => 'country_code', 'key' => 'Sweden', 'value' => '46'],
            [ 'group' => 'country_code', 'key' => 'Switzerland', 'value' => '41'],
            [ 'group' => 'country_code', 'key' => 'Syrian Arab Republic', 'value' => '963'],
            [ 'group' => 'country_code', 'key' => 'Taiwan', 'value' => '886'],
            [ 'group' => 'country_code', 'key' => 'Tajikistan', 'value' => '992'],
            [ 'group' => 'country_code', 'key' => 'Tanzania', 'value' => '255'],
            [ 'group' => 'country_code', 'key' => 'Thailand', 'value' => '66'],
            [ 'group' => 'country_code', 'key' => 'Timor-Leste (East Timor)', 'value' => '670'],
            [ 'group' => 'country_code', 'key' => 'Togo', 'value' => '228'],
            [ 'group' => 'country_code', 'key' => 'Tokelau', 'value' => '690'],
            [ 'group' => 'country_code', 'key' => 'Tonga', 'value' => '676'],
            [ 'group' => 'country_code', 'key' => 'Trinidad and Tobago', 'value' => '1 868'],
            [ 'group' => 'country_code', 'key' => 'Tunisia', 'value' => '216'],
            [ 'group' => 'country_code', 'key' => 'Turkey', 'value' => '90'],
            [ 'group' => 'country_code', 'key' => 'Turkmenistan', 'value' => '993'],
            [ 'group' => 'country_code', 'key' => 'Turks and Caicos Islands', 'value' => '1 649'],
            [ 'group' => 'country_code', 'key' => 'Tuvalu', 'value' => '688'],
            [ 'group' => 'country_code', 'key' => 'Uganda', 'value' => '256'],
            [ 'group' => 'country_code', 'key' => 'Ukraine', 'value' => '380'],
            [ 'group' => 'country_code', 'key' => 'United Arab Emirates', 'value' => '971'],
            [ 'group' => 'country_code', 'key' => 'United Kingdom', 'value' => '44'],
            [ 'group' => 'country_code', 'key' => 'United States', 'value' => '1'],
            [ 'group' => 'country_code', 'key' => 'US Minor Outlying Islands', 'value' => '808'],
            [ 'group' => 'country_code', 'key' => 'Uruguay', 'value' => '598'],
            [ 'group' => 'country_code', 'key' => 'Uzbekistan', 'value' => '998'],
            [ 'group' => 'country_code', 'key' => 'Vanuatu', 'value' => '678'],
            [ 'group' => 'country_code', 'key' => 'Vatican City State (Holy See)', 'value' => '379'],
            [ 'group' => 'country_code', 'key' => 'Venezuela', 'value' => '58'],
            [ 'group' => 'country_code', 'key' => 'Viet Nam', 'value' => '84'],
            [ 'group' => 'country_code', 'key' => 'Virgin Islands, British', 'value' => '1284'],
            [ 'group' => 'country_code', 'key' => 'Virgin Islands, U.S.', 'value' => '1340'],
            [ 'group' => 'country_code', 'key' => 'Wallis and Futuna', 'value' => '681'],
            [ 'group' => 'country_code', 'key' => 'Western Sahara', 'value' => '212'],
            [ 'group' => 'country_code', 'key' => 'Yemen', 'value' => '967'],
            [ 'group' => 'country_code', 'key' => 'Zambia', 'value' => '260'],
            [ 'group' => 'country_code', 'key' => 'Zimbabwe', 'value' => '263']
        ]);
    }
}
