<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('category')->insert([
            [ 'group' => 'country', 'value' => 'AF', 'key' => 'Afghanistan'],
            [ 'group' => 'country', 'value' => 'AX', 'key' => 'Aland Islands'],
            [ 'group' => 'country', 'value' => 'AL', 'key' => 'Albania'],
            [ 'group' => 'country', 'value' => 'DZ', 'key' => 'Algeria'],
            [ 'group' => 'country', 'value' => 'AS', 'key' => 'American Samoa'],
            [ 'group' => 'country', 'value' => 'AD', 'key' => 'Andorra'],
            [ 'group' => 'country', 'value' => 'AO', 'key' => 'Angola'],
            [ 'group' => 'country', 'value' => 'AI', 'key' => 'Anguilla'],
            [ 'group' => 'country', 'value' => 'AQ', 'key' => 'Antarctica'],
            [ 'group' => 'country', 'value' => 'AG', 'key' => 'Antigua and Barbuda'],
            [ 'group' => 'country', 'value' => 'AR', 'key' => 'Argentina'],
            [ 'group' => 'country', 'value' => 'AM', 'key' => 'Armenia'],
            [ 'group' => 'country', 'value' => 'AW', 'key' => 'Aruba'],
            [ 'group' => 'country', 'value' => 'AU', 'key' => 'Australia'],
            [ 'group' => 'country', 'value' => 'AT', 'key' => 'Austria'],
            [ 'group' => 'country', 'value' => 'AZ', 'key' => 'Azerbaijan'],
            [ 'group' => 'country', 'value' => 'BS', 'key' => 'Bahamas'],
            [ 'group' => 'country', 'value' => 'BH', 'key' => 'Bahrain'],
            [ 'group' => 'country', 'value' => 'BD', 'key' => 'Bangladesh'],
            [ 'group' => 'country', 'value' => 'BB', 'key' => 'Barbados'],
            [ 'group' => 'country', 'value' => 'BY', 'key' => 'Belarus'],
            [ 'group' => 'country', 'value' => 'BE', 'key' => 'Belgium'],
            [ 'group' => 'country', 'value' => 'BZ', 'key' => 'Belize'],
            [ 'group' => 'country', 'value' => 'BJ', 'key' => 'Benin'],
            [ 'group' => 'country', 'value' => 'BM', 'key' => 'Bermuda'],
            [ 'group' => 'country', 'value' => 'BT', 'key' => 'Bhutan'],
            [ 'group' => 'country', 'value' => 'BO', 'key' => 'Bolivia'],
            [ 'group' => 'country', 'value' => 'BQ', 'key' => 'Bonaire, Saint Eustatius and Saba'],
            [ 'group' => 'country', 'value' => 'BA', 'key' => 'Bosnia and Herzegovina'],
            [ 'group' => 'country', 'value' => 'BW', 'key' => 'Botswana'],
            [ 'group' => 'country', 'value' => 'BV', 'key' => 'Bouvet Island'],
            [ 'group' => 'country', 'value' => 'BR', 'key' => 'Brazil'],
            [ 'group' => 'country', 'value' => 'IO', 'key' => 'British Indian Ocean Territory'],
            [ 'group' => 'country', 'value' => 'VG', 'key' => 'British Virgin Islands'],
            [ 'group' => 'country', 'value' => 'BN', 'key' => 'Brunei'],
            [ 'group' => 'country', 'value' => 'BG', 'key' => 'Bulgaria'],
            [ 'group' => 'country', 'value' => 'BF', 'key' => 'Burkina Faso'],
            [ 'group' => 'country', 'value' => 'BI', 'key' => 'Burundi'],
            [ 'group' => 'country', 'value' => 'KH', 'key' => 'Cambodia'],
            [ 'group' => 'country', 'value' => 'CM', 'key' => 'Cameroon'],
            [ 'group' => 'country', 'value' => 'CA', 'key' => 'Canada'],
            [ 'group' => 'country', 'value' => 'CV', 'key' => 'Cape Verde'],
            [ 'group' => 'country', 'value' => 'KY', 'key' => 'Cayman Islands'],
            [ 'group' => 'country', 'value' => 'CF', 'key' => 'Central African Republic'],
            [ 'group' => 'country', 'value' => 'TD', 'key' => 'Chad'],
            [ 'group' => 'country', 'value' => 'CL', 'key' => 'Chile'],
            [ 'group' => 'country', 'value' => 'CN', 'key' => 'China'],
            [ 'group' => 'country', 'value' => 'CX', 'key' => 'Christmas Island'],
            [ 'group' => 'country', 'value' => 'CC', 'key' => 'Cocos Islands'],
            [ 'group' => 'country', 'value' => 'CO', 'key' => 'Colombia'],
            [ 'group' => 'country', 'value' => 'KM', 'key' => 'Comoros'],
            [ 'group' => 'country', 'value' => 'CK', 'key' => 'Cook Islands'],
            [ 'group' => 'country', 'value' => 'CR', 'key' => 'Costa Rica'],
            [ 'group' => 'country', 'value' => 'HR', 'key' => 'Croatia'],
            [ 'group' => 'country', 'value' => 'CU', 'key' => 'Cuba'],
            [ 'group' => 'country', 'value' => 'CW', 'key' => 'Curacao'],
            [ 'group' => 'country', 'value' => 'CY', 'key' => 'Cyprus'],
            [ 'group' => 'country', 'value' => 'CZ', 'key' => 'Czech Republic'],
            [ 'group' => 'country', 'value' => 'CD', 'key' => 'Democratic Republic of the Congo'],
            [ 'group' => 'country', 'value' => 'DK', 'key' => 'Denmark'],
            [ 'group' => 'country', 'value' => 'DJ', 'key' => 'Djibouti'],
            [ 'group' => 'country', 'value' => 'DM', 'key' => 'Dominica'],
            [ 'group' => 'country', 'value' => 'DO', 'key' => 'Dominican Republic'],
            [ 'group' => 'country', 'value' => 'TL', 'key' => 'East Timor'],
            [ 'group' => 'country', 'value' => 'EC', 'key' => 'Ecuador'],
            [ 'group' => 'country', 'value' => 'EG', 'key' => 'Egypt'],
            [ 'group' => 'country', 'value' => 'SV', 'key' => 'El Salvador'],
            [ 'group' => 'country', 'value' => 'GQ', 'key' => 'Equatorial Guinea'],
            [ 'group' => 'country', 'value' => 'ER', 'key' => 'Eritrea'],
            [ 'group' => 'country', 'value' => 'EE', 'key' => 'Estonia'],
            [ 'group' => 'country', 'value' => 'ET', 'key' => 'Ethiopia'],
            [ 'group' => 'country', 'value' => 'FK', 'key' => 'Falkland Islands'],
            [ 'group' => 'country', 'value' => 'FO', 'key' => 'Faroe Islands'],
            [ 'group' => 'country', 'value' => 'FJ', 'key' => 'Fiji'],
            [ 'group' => 'country', 'value' => 'FI', 'key' => 'Finland'],
            [ 'group' => 'country', 'value' => 'FR', 'key' => 'France'],
            [ 'group' => 'country', 'value' => 'GF', 'key' => 'French Guiana'],
            [ 'group' => 'country', 'value' => 'PF', 'key' => 'French Polynesia'],
            [ 'group' => 'country', 'value' => 'TF', 'key' => 'French Southern Territories'],
            [ 'group' => 'country', 'value' => 'GA', 'key' => 'Gabon'],
            [ 'group' => 'country', 'value' => 'GM', 'key' => 'Gambia'],
            [ 'group' => 'country', 'value' => 'GE', 'key' => 'Georgia'],
            [ 'group' => 'country', 'value' => 'DE', 'key' => 'Germany'],
            [ 'group' => 'country', 'value' => 'GH', 'key' => 'Ghana'],
            [ 'group' => 'country', 'value' => 'GI', 'key' => 'Gibraltar'],
            [ 'group' => 'country', 'value' => 'GR', 'key' => 'Greece'],
            [ 'group' => 'country', 'value' => 'GL', 'key' => 'Greenland'],
            [ 'group' => 'country', 'value' => 'GD', 'key' => 'Grenada'],
            [ 'group' => 'country', 'value' => 'GP', 'key' => 'Guadeloupe'],
            [ 'group' => 'country', 'value' => 'GU', 'key' => 'Guam'],
            [ 'group' => 'country', 'value' => 'GT', 'key' => 'Guatemala'],
            [ 'group' => 'country', 'value' => 'GG', 'key' => 'Guernsey'],
            [ 'group' => 'country', 'value' => 'GN', 'key' => 'Guinea'],
            [ 'group' => 'country', 'value' => 'GW', 'key' => 'Guinea-Bissau'],
            [ 'group' => 'country', 'value' => 'GY', 'key' => 'Guyana'],
            [ 'group' => 'country', 'value' => 'HT', 'key' => 'Haiti'],
            [ 'group' => 'country', 'value' => 'HM', 'key' => 'Heard Island and McDonald Islands'],
            [ 'group' => 'country', 'value' => 'HN', 'key' => 'Honduras'],
            [ 'group' => 'country', 'value' => 'HK', 'key' => 'Hong Kong'],
            [ 'group' => 'country', 'value' => 'HU', 'key' => 'Hungary'],
            [ 'group' => 'country', 'value' => 'IS', 'key' => 'Iceland'],
            [ 'group' => 'country', 'value' => 'IN', 'key' => 'India'],
            [ 'group' => 'country', 'value' => 'ID', 'key' => 'Indonesia'],
            [ 'group' => 'country', 'value' => 'IR', 'key' => 'Iran'],
            [ 'group' => 'country', 'value' => 'IQ', 'key' => 'Iraq'],
            [ 'group' => 'country', 'value' => 'IE', 'key' => 'Ireland'],
            [ 'group' => 'country', 'value' => 'IM', 'key' => 'Isle of Man'],
            [ 'group' => 'country', 'value' => 'IL', 'key' => 'Israel'],
            [ 'group' => 'country', 'value' => 'IT', 'key' => 'Italy'],
            [ 'group' => 'country', 'value' => 'CI', 'key' => 'Ivory Coast'],
            [ 'group' => 'country', 'value' => 'JM', 'key' => 'Jamaica'],
            [ 'group' => 'country', 'value' => 'JP', 'key' => 'Japan'],
            [ 'group' => 'country', 'value' => 'JE', 'key' => 'Jersey'],
            [ 'group' => 'country', 'value' => 'JO', 'key' => 'Jordan'],
            [ 'group' => 'country', 'value' => 'KZ', 'key' => 'Kazakhstan'],
            [ 'group' => 'country', 'value' => 'KE', 'key' => 'Kenya'],
            [ 'group' => 'country', 'value' => 'KI', 'key' => 'Kiribati'],
            [ 'group' => 'country', 'value' => 'XK', 'key' => 'Kosovo'],
            [ 'group' => 'country', 'value' => 'KW', 'key' => 'Kuwait'],
            [ 'group' => 'country', 'value' => 'KG', 'key' => 'Kyrgyzstan'],
            [ 'group' => 'country', 'value' => 'LA', 'key' => 'Laos'],
            [ 'group' => 'country', 'value' => 'LV', 'key' => 'Latvia'],
            [ 'group' => 'country', 'value' => 'LB', 'key' => 'Lebanon'],
            [ 'group' => 'country', 'value' => 'LS', 'key' => 'Lesotho'],
            [ 'group' => 'country', 'value' => 'LR', 'key' => 'Liberia'],
            [ 'group' => 'country', 'value' => 'LY', 'key' => 'Libya'],
            [ 'group' => 'country', 'value' => 'LI', 'key' => 'Liechtenstein'],
            [ 'group' => 'country', 'value' => 'LT', 'key' => 'Lithuania'],
            [ 'group' => 'country', 'value' => 'LU', 'key' => 'Luxembourg'],
            [ 'group' => 'country', 'value' => 'MO', 'key' => 'Macao'],
            [ 'group' => 'country', 'value' => 'MK', 'key' => 'Macedonia'],
            [ 'group' => 'country', 'value' => 'MG', 'key' => 'Madagascar'],
            [ 'group' => 'country', 'value' => 'MW', 'key' => 'Malawi'],
            [ 'group' => 'country', 'value' => 'MY', 'key' => 'Malaysia'],
            [ 'group' => 'country', 'value' => 'MV', 'key' => 'Maldives'],
            [ 'group' => 'country', 'value' => 'ML', 'key' => 'Mali'],
            [ 'group' => 'country', 'value' => 'MT', 'key' => 'Malta'],
            [ 'group' => 'country', 'value' => 'MH', 'key' => 'Marshall Islands'],
            [ 'group' => 'country', 'value' => 'MQ', 'key' => 'Martinique'],
            [ 'group' => 'country', 'value' => 'MR', 'key' => 'Mauritania'],
            [ 'group' => 'country', 'value' => 'MU', 'key' => 'Mauritius'],
            [ 'group' => 'country', 'value' => 'YT', 'key' => 'Mayotte'],
            [ 'group' => 'country', 'value' => 'MX', 'key' => 'Mexico'],
            [ 'group' => 'country', 'value' => 'FM', 'key' => 'Micronesia'],
            [ 'group' => 'country', 'value' => 'MD', 'key' => 'Moldova'],
            [ 'group' => 'country', 'value' => 'MC', 'key' => 'Monaco'],
            [ 'group' => 'country', 'value' => 'MN', 'key' => 'Mongolia'],
            [ 'group' => 'country', 'value' => 'ME', 'key' => 'Montenegro'],
            [ 'group' => 'country', 'value' => 'MS', 'key' => 'Montserrat'],
            [ 'group' => 'country', 'value' => 'MA', 'key' => 'Morocco'],
            [ 'group' => 'country', 'value' => 'MZ', 'key' => 'Mozambique'],
            [ 'group' => 'country', 'value' => 'MM', 'key' => 'Myanmar'],
            [ 'group' => 'country', 'value' => 'NA', 'key' => 'Namibia'],
            [ 'group' => 'country', 'value' => 'NR', 'key' => 'Nauru'],
            [ 'group' => 'country', 'value' => 'NP', 'key' => 'Nepal'],
            [ 'group' => 'country', 'value' => 'NL', 'key' => 'Netherlands'],
            [ 'group' => 'country', 'value' => 'NC', 'key' => 'New Caledonia'],
            [ 'group' => 'country', 'value' => 'NZ', 'key' => 'New Zealand'],
            [ 'group' => 'country', 'value' => 'NI', 'key' => 'Nicaragua'],
            [ 'group' => 'country', 'value' => 'NE', 'key' => 'Niger'],
            [ 'group' => 'country', 'value' => 'NG', 'key' => 'Nigeria'],
            [ 'group' => 'country', 'value' => 'NU', 'key' => 'Niue'],
            [ 'group' => 'country', 'value' => 'NF', 'key' => 'Norfolk Island'],
            [ 'group' => 'country', 'value' => 'KP', 'key' => 'North Korea'],
            [ 'group' => 'country', 'value' => 'MP', 'key' => 'Northern Mariana Islands'],
            [ 'group' => 'country', 'value' => 'NO', 'key' => 'Norway'],
            [ 'group' => 'country', 'value' => 'OM', 'key' => 'Oman'],
            [ 'group' => 'country', 'value' => 'PK', 'key' => 'Pakistan'],
            [ 'group' => 'country', 'value' => 'PW', 'key' => 'Palau'],
            [ 'group' => 'country', 'value' => 'PS', 'key' => 'Palestinian Territory'],
            [ 'group' => 'country', 'value' => 'PA', 'key' => 'Panama'],
            [ 'group' => 'country', 'value' => 'PG', 'key' => 'Papua New Guinea'],
            [ 'group' => 'country', 'value' => 'PY', 'key' => 'Paraguay'],
            [ 'group' => 'country', 'value' => 'PE', 'key' => 'Peru'],
            [ 'group' => 'country', 'value' => 'PH', 'key' => 'Philippines'],
            [ 'group' => 'country', 'value' => 'PN', 'key' => 'Pitcairn'],
            [ 'group' => 'country', 'value' => 'PL', 'key' => 'Poland'],
            [ 'group' => 'country', 'value' => 'PT', 'key' => 'Portugal'],
            [ 'group' => 'country', 'value' => 'PR', 'key' => 'Puerto Rico'],
            [ 'group' => 'country', 'value' => 'QA', 'key' => 'Qatar'],
            [ 'group' => 'country', 'value' => 'CG', 'key' => 'Republic of the Congo'],
            [ 'group' => 'country', 'value' => 'RE', 'key' => 'Reunion'],
            [ 'group' => 'country', 'value' => 'RO', 'key' => 'Romania'],
            [ 'group' => 'country', 'value' => 'RU', 'key' => 'Russia'],
            [ 'group' => 'country', 'value' => 'RW', 'key' => 'Rwanda'],
            [ 'group' => 'country', 'value' => 'BL', 'key' => 'Saint Barthelemy'],
            [ 'group' => 'country', 'value' => 'SH', 'key' => 'Saint Helena'],
            [ 'group' => 'country', 'value' => 'KN', 'key' => 'Saint Kitts and Nevis'],
            [ 'group' => 'country', 'value' => 'LC', 'key' => 'Saint Lucia'],
            [ 'group' => 'country', 'value' => 'MF', 'key' => 'Saint Martin'],
            [ 'group' => 'country', 'value' => 'PM', 'key' => 'Saint Pierre and Miquelon'],
            [ 'group' => 'country', 'value' => 'VC', 'key' => 'Saint Vincent and the Grenadines'],
            [ 'group' => 'country', 'value' => 'WS', 'key' => 'Samoa'],
            [ 'group' => 'country', 'value' => 'SM', 'key' => 'San Marino'],
            [ 'group' => 'country', 'value' => 'ST', 'key' => 'Sao Tome and Principe'],
            [ 'group' => 'country', 'value' => 'SA', 'key' => 'Saudi Arabia'],
            [ 'group' => 'country', 'value' => 'SN', 'key' => 'Senegal'],
            [ 'group' => 'country', 'value' => 'RS', 'key' => 'Serbia'],
            [ 'group' => 'country', 'value' => 'SC', 'key' => 'Seychelles'],
            [ 'group' => 'country', 'value' => 'SL', 'key' => 'Sierra Leone'],
            [ 'group' => 'country', 'value' => 'SG', 'key' => 'Singapore'],
            [ 'group' => 'country', 'value' => 'SX', 'key' => 'Sint Maarten'],
            [ 'group' => 'country', 'value' => 'SK', 'key' => 'Slovakia'],
            [ 'group' => 'country', 'value' => 'SI', 'key' => 'Slovenia'],
            [ 'group' => 'country', 'value' => 'SB', 'key' => 'Solomon Islands'],
            [ 'group' => 'country', 'value' => 'SO', 'key' => 'Somalia'],
            [ 'group' => 'country', 'value' => 'ZA', 'key' => 'South Africa'],
            [ 'group' => 'country', 'value' => 'GS', 'key' => 'South Georgia and the South Sandwich Islands'],
            [ 'group' => 'country', 'value' => 'KR', 'key' => 'South Korea'],
            [ 'group' => 'country', 'value' => 'SS', 'key' => 'South Sudan'],
            [ 'group' => 'country', 'value' => 'ES', 'key' => 'Spain'],
            [ 'group' => 'country', 'value' => 'LK', 'key' => 'Sri Lanka'],
            [ 'group' => 'country', 'value' => 'SD', 'key' => 'Sudan'],
            [ 'group' => 'country', 'value' => 'SR', 'key' => 'Suriname'],
            [ 'group' => 'country', 'value' => 'SJ', 'key' => 'Svalbard and Jan Mayen'],
            [ 'group' => 'country', 'value' => 'SZ', 'key' => 'Swaziland'],
            [ 'group' => 'country', 'value' => 'SE', 'key' => 'Sweden'],
            [ 'group' => 'country', 'value' => 'CH', 'key' => 'Switzerland'],
            [ 'group' => 'country', 'value' => 'SY', 'key' => 'Syria'],
            [ 'group' => 'country', 'value' => 'TW', 'key' => 'Taiwan'],
            [ 'group' => 'country', 'value' => 'TJ', 'key' => 'Tajikistan'],
            [ 'group' => 'country', 'value' => 'TZ', 'key' => 'Tanzania'],
            [ 'group' => 'country', 'value' => 'TH', 'key' => 'Thailand'],
            [ 'group' => 'country', 'value' => 'TG', 'key' => 'Togo'],
            [ 'group' => 'country', 'value' => 'TK', 'key' => 'Tokelau'],
            [ 'group' => 'country', 'value' => 'TO', 'key' => 'Tonga'],
            [ 'group' => 'country', 'value' => 'TT', 'key' => 'Trinidad and Tobago'],
            [ 'group' => 'country', 'value' => 'TN', 'key' => 'Tunisia'],
            [ 'group' => 'country', 'value' => 'TR', 'key' => 'Turkey'],
            [ 'group' => 'country', 'value' => 'TM', 'key' => 'Turkmenistan'],
            [ 'group' => 'country', 'value' => 'TC', 'key' => 'Turks and Caicos Islands'],
            [ 'group' => 'country', 'value' => 'TV', 'key' => 'Tuvalu'],
            [ 'group' => 'country', 'value' => 'VI', 'key' => 'U.S. Virgin Islands'],
            [ 'group' => 'country', 'value' => 'UG', 'key' => 'Uganda'],
            [ 'group' => 'country', 'value' => 'UA', 'key' => 'Ukraine'],
            [ 'group' => 'country', 'value' => 'AE', 'key' => 'United Arab Emirates'],
            [ 'group' => 'country', 'value' => 'GB', 'key' => 'United Kingdom'],
            [ 'group' => 'country', 'value' => 'US', 'key' => 'United States'],
            [ 'group' => 'country', 'value' => 'UM', 'key' => 'United States Minor Outlying Islands'],
            [ 'group' => 'country', 'value' => 'UY', 'key' => 'Uruguay'],
            [ 'group' => 'country', 'value' => 'UZ', 'key' => 'Uzbekistan'],
            [ 'group' => 'country', 'value' => 'VU', 'key' => 'Vanuatu'],
            [ 'group' => 'country', 'value' => 'VA', 'key' => 'Vatican'],
            [ 'group' => 'country', 'value' => 'VE', 'key' => 'Venezuela'],
            [ 'group' => 'country', 'value' => 'VN', 'key' => 'Vietnam'],
            [ 'group' => 'country', 'value' => 'WF', 'key' => 'Wallis and Futuna'],
            [ 'group' => 'country', 'value' => 'EH', 'key' => 'Western Sahara'],
            [ 'group' => 'country', 'value' => 'YE', 'key' => 'Yemen'],
            [ 'group' => 'country', 'value' => 'ZM', 'key' => 'Zambia'],
            [ 'group' => 'country', 'value' => 'ZW', 'key' => 'Zimbabwe'],
        ]);
    }
}

